main.o: main.cpp ../video/VideoCapture.hpp ../button/button.hpp
	g++ -I/usr/local/include/opencv4 -L/usr/local/lib/ -Wall -c -g main.cpp ../video/VideoCapture.hpp ../button/button.hpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_video -lopencv_videoio

mainDebug.o: main.cpp ../video/VideoCapture.hpp ../button/button.hpp
	g++ -I/usr/local/include/opencv4 -L/usr/local/lib/ -Wall -c main.cpp ../video/VideoCapture.hpp ../button/button.hpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_video -lopencv_videoio

